# Generated by Django 3.2 on 2021-04-12 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car',
            new_name='Model',
        ),
    ]
