# Generated by Django 3.2 on 2021-04-12 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rename_car_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model',
            options={'ordering': ['model_name']},
        ),
        migrations.AddField(
            model_name='model',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.brand'),
        ),
    ]
